services:
  talos-agent:
    build: .
    # NOTE: Run ./scripts/build_container_image.sh to retrieve the digest.
    image: ghcr.io/lukaw3d/talos:latest-agent@sha256:b3ec28d4a8bc083c0ba92bc4caa881129a45738d019f2be224083b5a347ccd97
    container_name: talos-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
    volumes:
      - talos_data:/app/data
    ports:
      - "8000:8000"

volumes:
  talos_data:
